# Generated by Django 4.2.7 on 2023-11-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('body_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pulse_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('respiration_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('oxygen_level', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('visit_reason', models.CharField(max_length=256, null=True)),
                ('notes', models.TextField(null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
